### PR TITLE
Added methods to change button background and text color

### PR DESCRIPTION
**Pull request by carvalho2707**
This PR will allow the developers to customise the button background color and button text color.
This applies to confirm, neutral and cancel button if configured.

### CODE REVIEW

**Comment by F0RIS** [comment]
Thanks! But this feature isnt finished

Where is rounding?
image

And what about regular dialogs? You forgot to set default colors values
image

**Comment by carvalho2707** [comment]
You're correct, I'll update the PR

**Comment by carvalho2707** [comment]
@F0RIS Followed your comments and the logic is complete now.

**Comment by F0RIS** [comment]
This still breakes gray buttons color. And stoke wasnt visible bcz it has same color as solid color.
Anyway I took what you did and reworked

**Pull request closed without merging**
